Funcionarios_Ambev/Models/Funcionario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Funcionarios_Ambev.Models
{
    [Table("dbo.Funcioanrio")]
    public class Funcionario
    {
        [Key,Column("FuncionarioId")]
        public int ID { get; set; }

        public string Nome { get; set; }

        public int Idade { get; set; }
    }
}

Funcionarios_Ambev/Models/Sql_AmbevContext.cs
using System.Data.Entity;

namespace Funcionarios_Ambev.Models
{
    public class Sql_AmbevContext : DbContext
    {
        public Sql_AmbevContext() : base("name=AmbevContext")
        {
        }
        public DbSet<Funcionario> Funcionarios { get; set; }
    }
}

Funcionarios_Ambev/Controllers/FuncionariosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Funcionarios_Ambev.Models;

namespace Funcionarios_Ambev.Controllers
{
    public class FuncionariosController : Controller
    {
        private Sql_AmbevContext db = new Sql_AmbevContext();
        
        public ActionResult Index()
        {
            return View(db.Funcionarios.ToList());
        }

        public ActionResult Cadastrar()
        {
            return View();
        }
               
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarCadastro([Bind(Include = "ID,Nome,Idade")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Funcionarios.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        
        public ActionResult Editar(int? id)
        {           
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarEdicao([Bind(Include = "ID,Nome,Idade")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

       
        public ActionResult Deletar(int? id)
        {           
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        
        [HttpPost, ActionName("DeletarFuncionario")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarFuncionario(int id)
        {
            Funcionario funcionario = db.Funcionarios.Find(id);
            db.Funcionarios.Remove(funcionario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Funcionarios_Ambev/Views/Funcionarios/Cadastrar.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("SalvarCadastro","Funcionarios"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadastro de Funcionairo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @type="text" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" style = "width:100%" } />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<link href="~/Content/Site.css" rel="stylesheet" />
<div id="boxImagem">
    <img width="60%" height="100%" src="~/img/ambev.png" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Funcionarios_Ambev/Views/Funcionarios/Create.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Funcionario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Funcionarios_Ambev/Views/Funcionarios/Deletar.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir Funcionario</h2>

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

    </dl>

    @using (Html.BeginForm("DeletarFuncionario", "Funcionarios"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.ID)
        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>
<link href="~/Content/Site.css" rel="stylesheet" />
<div id="boxImagem">
    <img width="60%" height="100%" src="~/img/ambev.png" />
</div>

Funcionarios_Ambev/Views/Funcionarios/Delete.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Funcionarios_Ambev/Views/Funcionarios/Edit.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Funcionario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Funcionarios_Ambev/Views/Funcionarios/Editar.cshtml
@model Funcionarios_Ambev.Models.Funcionario

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("SalvarEdicao", "Funcionarios"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar Funcionario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<link href="~/Content/Site.css" rel="stylesheet" />
<div id="boxImagem">
    <img width="60%" height="100%" src="~/img/ambev.png" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Funcionarios_Ambev/Views/Funcionarios/Index.cshtml
@model IEnumerable<Funcionarios_Ambev.Models.Funcionario>

@{
    ViewBag.Title = "Index";
}

<h2>Funcionarios</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.ID }, new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Deletar", "Deletar", new { id = item.ID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Cadastrar Novo Funcionario Funcionario", "Cadastrar", "", new { @class = "btn btn-success", @style = "width:100%" })
</p>
<link href="~/Content/Site.css" rel="stylesheet" />
<div id="boxImagem">
    <img width="60%" height="100%" src="~/img/ambev.png" />
</div>

Funcionarios_Ambev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ambev</title>
    @Styles.Render("~/Content/bootstrap.css")

    <link href="~/Content/Site.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="CorNavBar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ambev", "Index", "Funcionarios", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    </ul>
                </div>*@
        </div>
    </div>    

    
    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer >
            <p>&copy; @DateTime.Now.Year | Ambev</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>